version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: sms-gateway-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sms_gateway
      MYSQL_USER: smsuser
      MYSQL_PASSWORD: smspassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migration:/docker-entrypoint-initdb.d

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: sms-gateway-redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # SMS Provider Mock
  sms-provider-mock:
    build:
      context: ./cmd/sms_provider_mock
      dockerfile: deploy/dockerFile
    container_name: sms-provider-mock
    restart: always
    env_file: .env
    ports:
      - "8081:8081"

  # SMS Gateway Application
  app:
    build:
      context: .
      dockerfile: deploy/dockerFile
    container_name: sms-gateway-app
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
      - sms-provider-mock

volumes:
  mysql_data:
  redis_data:

